#rosalind_ba10h
'''
HMM Parameter Estimation Problem

Given: A sequence of emitted symbols x = x1 . . . xn in an alphabet ∑ and 
a path π = π1 . . . πn generated by a k-state HMM with unknown transition 
and emission probabilities.

Return: A matrix of transition probabilities Transition and a matrix of 
emission probabilities Emission that maximize Pr(x,π) over all possible 
matrices of transition and emission probabilities.
'''

from pandas import DataFrame
from io import StringIO

f = open('rosalind_ba10h.txt').read().rstrip().split('--------\n')
x = list(f[0].rstrip())
alphabet = f[1].rstrip().split()
path = list(f[2].rstrip())
states = f[3].rstrip().split()    

transitions = DataFrame(data=0.0, index=states, columns=states)
emissions   = DataFrame(data=0.0, index=states, columns=alphabet)

for t in zip(path[:-1], path[1:]):
    transitions.loc[t] += 1

for a in zip(path, x):
    emissions.loc[a] += 1

transitions = transitions.div(transitions.sum(1) + 1e-10, axis=0).round(3)
emissions = emissions.div(emissions.sum(1) + 1e-10, axis=0).round(3)

f = StringIO()
transitions.to_csv(f, sep='\t', float_format='%g')
f.write('--------\n')
emissions.to_csv(f, sep='\t', float_format='%g')

open('rosalind_ba10h_sub.txt', 'wt').write(f.getvalue().rstrip())
